name: Japanese Car News -> LINE (Flex)

on:
  schedule:
    - cron: '0 3 * * *'  # 12:00 JST
    - cron: '0 6 * * *'  # 15:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LINE Flex bot
        env:
          LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
        run: |
          python japanese_car_news_line_flex.py

      - name: Commit sent_ids.json (if changed)
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add sent_ids.json
          git commit -m "Update sent_ids.json" || echo "No changes to commit"
          git push
